### ISSUE TITLE
DiscImageChef error writing multisession disc on Alcohol 120% format

### ISSUE THREAD

**Issue by SilasLaspada** [claunia/DiscImageChef#179]
Trying to read a CD-XA disc with multiple tracks, including 6 audio tracks in the 1st session, fails. It is (wrongfully?) identified as just "CD" instead of "CDROMXA", and it reports bad sectors that Alcohol 120% says aren't there, and after it retries the sectors it crashes with the error 
> Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at DiscImageChef.DiscImages.Alcohol120.Close() in C:\Users\silas\Desktop\GIT\Disc\DiscImageChef.DiscImages\Alcohol120.cs:line 2010
   at DiscImageChef.Core.Devices.Dumping.CompactDisc.Dump(Device dev, String devicePath, IWritableImage outputPlugin, UInt16 retryPasses, Boolean force, Boolean dumpRaw, Boolean persistent, Boolean stopOnError, MediaType& dskType, Resume& resume, DumpLog& dumpLog, Boolean dumpLeadIn, Encoding encoding, String outputPrefix, String outputPath, Dictionary`2 formatOptions, CICMMetadataType preSidecar, UInt32 skip, Boolean nometadata, Boolean notrim) in C:\Users\silas\Desktop\GIT\Disc\DiscImageChef.Core\Devices\Dumping\CompactDisc.cs:line 1362
   at DiscImageChef.Core.Devices.Dumping.Mmc.Dump(Device dev, String devicePath, IWritableImage outputPlugin, UInt16 retryPasses, Boolean force, Boolean dumpRaw, Boolean persistent, Boolean stopOnError, MediaType& dskType, Resume& resume, DumpLog& dumpLog, Boolean dumpLeadIn, Encoding encoding, String outputPrefix, String outputPath, Dictionary`2 formatOptions, CICMMetadataType preSidecar, UInt32 skip, Boolean nometadata, Boolean notrim) in C:\Users\silas\Desktop\GIT\Disc\DiscImageChef.Core\Devices\Dumping\MMC.cs:line 201
   at DiscImageChef.Core.Devices.Dumping.Scsi.Dump(Device dev, String devicePath, IWritableImage outputPlugin, UInt16 retryPasses, Boolean force, Boolean dumpRaw, Boolean persistent, Boolean stopOnError, Resume& resume, DumpLog& dumpLog, Boolean dumpLeadIn, Encoding encoding, String outputPrefix, String outputPath, Dictionary`2 formatOptions, CICMMetadataType preSidecar, UInt32 skip, Boolean nometadata, Boolean notrim) in C:\Users\silas\Desktop\GIT\Disc\DiscImageChef.Core\Devices\Dumping\SCSI.cs:line 212
   at DiscImageChef.Commands.DumpMedia.DoDumpMedia(DumpMediaOptions options) in C:\Users\silas\Desktop\GIT\Disc\DiscImageChef\Commands\DumpMedia.cs:line 228
   at DiscImageChef.MainClass.<>c.<Main>b__0_13(DumpMediaOptions opts) in C:\Users\silas\Desktop\GIT\Disc\DiscImageChef\Main.cs:line 149
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DiscImageChef.MainClass.Main(String[] args) in C:\Users\silas\Desktop\GIT\Disc\DiscImageChef\Main.cs:line 57

Converting the image made by Alcohol 120% stops immediately and says "Unable to open image format". The image file is at https://archive.org/details/OldElPasoRecipesForFamilyFun. Let me know if you need anything else! 
[Log.zip](https://github.com/claunia/DiscImageChef/files/2121113/Log.zip)

**Comment by claunia** [comment]
Alcohol 120% is known to say sectors do not fail in cases they do.

I will need all the files created with the media-info command with the -d option.

**Comment by claunia** [comment]
Also, does the dump work in another format, like dicformat or bin/cue?

**Comment by SilasLaspada** [comment]
Ok, I'll check dumping in another format. In the mean time, here's the results from media-info.
[BIN files.zip](https://github.com/claunia/DiscImageChef/files/2121198/BIN.files.zip)

**Comment by claunia** [comment]
@SilasLaspada I think it is, I can reproduce it with a copy.

**Comment by SilasLaspada** [comment]
Dumping it as CUE still misidentifies it as just CD and can't read some of the sectors, but it doesn't crash at the end. Also, the newest commit does allow me to convert it to CUE, albeit with significant differences from the image file that DiscImageChef made.
[Log for BIN+CUE.zip](https://github.com/claunia/DiscImageChef/files/2121269/Log.for.BIN.CUE.zip)

**Comment by claunia** [comment]
Ok I'll check it over the weekend.

**Comment by SilasLaspada** [comment]
The newest commit does help with the errors being reported (down from over 10,000 to about 300), but dumping it still finds bad sectors that Alcohol 120% doesn't see, and it still crashes with a very similar error message:
> Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at DiscImageChef.DiscImages.Alcohol120.Close() in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.DiscImages\Alcohol120.cs:line 2004
   at DiscImageChef.Core.Devices.Dumping.CompactDisc.Dump(Device dev, String devicePath, IWritableImage outputPlugin, UInt16 retryPasses, Boolean force, Boolean dumpRaw, Boolean persistent, Boolean stopOnError, MediaType& dskType, Resume& resume, DumpLog& dumpLog, Boolean dumpLeadIn, Encoding encoding, String outputPrefix, String outputPath, Dictionary`2 formatOptions, CICMMetadataType preSidecar, UInt32 skip, Boolean nometadata, Boolean notrim) in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.Core\Devices\Dumping\CompactDisc.cs:line 1576
   at DiscImageChef.Core.Devices.Dumping.Mmc.Dump(Device dev, String devicePath, IWritableImage outputPlugin, UInt16 retryPasses, Boolean force, Boolean dumpRaw, Boolean persistent, Boolean stopOnError, MediaType& dskType, Resume& resume, DumpLog& dumpLog, Boolean dumpLeadIn, Encoding encoding, String outputPrefix, String outputPath, Dictionary`2 formatOptions, CICMMetadataType preSidecar, UInt32 skip, Boolean nometadata, Boolean notrim) in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.Core\Devices\Dumping\MMC.cs:line 199
   at DiscImageChef.Core.Devices.Dumping.Scsi.Dump(Device dev, String devicePath, IWritableImage outputPlugin, UInt16 retryPasses, Boolean force, Boolean dumpRaw, Boolean persistent, Boolean stopOnError, Resume& resume, DumpLog& dumpLog, Boolean dumpLeadIn, Encoding encoding, String outputPrefix, String outputPath, Dictionary`2 formatOptions, CICMMetadataType preSidecar, UInt32 skip, Boolean nometadata, Boolean notrim) in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.Core\Devices\Dumping\SCSI.cs:line 212
   at DiscImageChef.Commands.DumpMedia.DoDumpMedia(DumpMediaOptions options)
   at DiscImageChef.MainClass.<>c.<Main>b__0_13(DumpMediaOptions opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DiscImageChef.MainClass.Main(String[] args)

[New logs.zip](https://github.com/claunia/DiscImageChef/files/2129612/New.logs.zip)

**Comment by claunia** [comment]
Because THIS bug is not solved yet, it affects only Alcohol format, try to dump the disc in other format and send me the log AND the output please. That's why I splitted your original report in several bugs.

**Comment by SilasLaspada** [comment]
It still finds bad sectors in the newest version, but it doesn't crash DiscImageChef now. I'm in the process of dumping it as cue right now, and I'll upload that as soon as it's done. 
[Logs.zip](https://github.com/claunia/DiscImageChef/files/2129938/Logs.zip)

**Comment by SilasLaspada** [comment]
I'm uploading the image files to drop box right now, but I noticed the bad sectors are found while making the cue files as well. Should I make a separate bug report for this since it's not just an issue with MDS? Also I double-checked the disc with ImgBurn just to make sure that there aren't any bad sectors (according to it at least).

**Comment by claunia** [comment]
For the bad sectors report and upload in but https://github.com/claunia/DiscImageChef/issues/181 please
