### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException crash running dump-media

### ISSUE THREAD

**Issue by SilasLaspada** [claunia/DiscImageChef#188]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [X] I was running DiscImageChef under Windows 10 x64 Version 1803..
* [X] ...using .NET Framework 4.7.2...
* [X] ...in 64-bit

### Description

Running dump-media immediately crashes DIC with the error: 
`Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at DiscImageChef.CommonTypes.PluginBase..ctor() in C:\Users\silas\Desktop\GIT\DIC\trunk\DiscImageChef.CommonTypes\PluginBase.cs:line 94
   at DiscImageChef.Commands.DumpMedia.DoDumpMedia(DumpMediaOptions options)
   at DiscImageChef.MainClass.<>c.<Main>b__0_13(DumpMediaOptions opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DiscImageChef.MainClass.Main(String[] args)`

My hardware setup is still the same, and the software should be unchanged as well. I have tried compiling it as debug and release in both Visual Studio 2017 and JetBrains Rider. I tested this with my CD/DVD drive, I can test with a USB floppy drive to if it will help.

### Exact command line used:

`.\DiscImageChef.exe dump-media -i I: -o "test.iso"`

**Comment by claunia** [comment]
@SilasLaspada use a previous commit version, I'm preparing some huge changes to the internals and I cannot guarantee every single commit to work.
