### ISSUE TITLE
Unhandled Exception after "Closing output file." while dumping floppy disk

### ISSUE THREAD

**Issue by SilasLaspada** [claunia/DiscImageChef#192]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [X] I was running DiscImageChef under Windows 10...
* [X] ...using .NET Framework 4.7.2...
* [X] ...in 64-bit

### Description

While dumping a floppy disk to .img using a USB floppy drive, DIC crashes after "Closing Output file." with   
"Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DiscImageChef.DiscImages.ZZZRawImage.Close() in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.DiscImages\ZZZRawImage\Write.cs:line 216
   at DiscImageChef.Core.Devices.Dumping.Sbc.Dump(Device dev, String devicePath, IWritableImage outputPlugin, UInt16 retryPasses, Boolean force, Boolean dumpRaw, Boolean persistent, Boolean stopOnError, Dictionary`2 mediaTags, MediaType& dskType, Boolean opticalDisc, Resume& resume, DumpLog& dumpLog, Encoding encoding, String outputPrefix, String outputPath, Dictionary`2 formatOptions, CICMMetadataType preSidecar, UInt32 skip, Boolean nometadata, Boolean notrim) in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.Core\Devices\Dumping\SBC.cs:line 764
   at DiscImageChef.Core.Devices.Dumping.Scsi.Dump(Device dev, String devicePath, IWritableImage outputPlugin, UInt16 retryPasses, Boolean force, Boolean dumpRaw, Boolean persistent, Boolean stopOnError, Resume& resume, DumpLog& dumpLog, Boolean dumpLeadIn, Encoding encoding, String outputPrefix, String outputPath, Dictionary`2 formatOptions, CICMMetadataType preSidecar, UInt32 skip, Boolean nometadata, Boolean notrim) in C:\Users\silas\Desktop\GIT\DiscImageChef\trunk\DiscImageChef.Core\Devices\Dumping\SCSI.cs:line 217
   at DiscImageChef.Commands.DumpMedia.DoDumpMedia(DumpMediaOptions options)
   at DiscImageChef.MainClass.<>c.<Main>b__0_13(DumpMediaOptions opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DiscImageChef.MainClass.Main(String[] args)"

It did not crash dumping a CD, and I do not have another USB floppy drive handy to test with right now. The image itself appears to have saved correctly.
[Logs+Image.zip](https://github.com/claunia/DiscImageChef/files/2271338/Logs%2BImage.zip)

**Comment by SilasLaspada** [comment]
This issue is still present on the newest commit and with a second USB floppy drive.

**Comment by SilasLaspada** [comment]
This still happens on the newest commit, and this time I verified that it crashes when dumping as both IMG and DICF.

**Comment by SilasLaspada** [comment]
Dumping a floppy disk to .img and .dicf no longer crashes on the newest commit, tested with two separate USB floppy drives and two separate floppy disks.
