### ISSUE TITLE
Aaru crashes on macOS when trying to list devices

### ISSUE THREAD

**Issue by InternalLoss** [claunia/DiscImageChef#672]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropriate:
* [ ] I was running Aaru under Windows [version here]...
* [ ] I was running Aaru under Linux [version here]...
* [X] I was running Aaru under macOS Monterey beta (21A5522h)
* [ ] ...in 32-bit
* [X] ...in 64-bit
* [X] ...using an Intel / AMD processor
* [ ] ...using an ARM or Apple Silicon processor

### Description

When trying to run `dev list`, the program crashes before the list is given.

### Exact command line used:

`aaru dev list`

### Expected behavior:
The device list to show my internal SSD and USB-connected disc drive.

### Actual behavior:
```
❯ sudo ./aaru dev list
aaru 5.2.0.3330
Copyright © 2011-2020 Natalia Portillo

Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Platform MacOSX not yet supported.
   at Aaru.Devices.Device.ListDevices(Boolean& isRemote, String& serverApplication, String& serverVersion, String& serverOperatingSystem, String& serverOperatingSystemVersion, String& serverArchitecture, String aaruRemote) in /home/claunia/Development/Aaru/Aaru/Aaru.Devices/Device/List.cs:line 89
   at Aaru.Commands.Device.ListDevicesCommand.Invoke(Boolean debug, Boolean verbose, String aaruRemoteHost)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Output of command execution with debug output enabled
This error does not occur with the `-d` parameter passed on either debug or regular.
```
❯ sudo ./aaru dev list -d
aaru 5.2.0.3330
Copyright © 2011-2020 Natalia Portillo

Error connecting to host.
No known devices attached.
Uploading statistics
```

**Comment by claunia** [comment]
`Platform MacOSX not yet supported.` not a bug

**Comment by InternalLoss** [comment]
oops, sorry!
