### ISSUE TITLE
Errorneous `Disc contains a hidden track...` leads to crash reading multisession CD in Plextor PX-760A

### ISSUE THREAD

**Issue by acridAxid** [claunia/DiscImageChef#685]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Device manufacturer

Plextor

### Device model

PX-760A

### Bus the device uses to attach to the computer

- [X] Parallel ATA
- [ ] Serial ATA
- [ ] SCSI (any)
- [ ] ATAPI (mark above if parallel or serial)
- [ ] USB
- [ ] FireWire
- [ ] PCMCIA
- [ ] SecureDigital
- [ ] MultiMediaCard

### What were you doing when it failed?

- [X] I was dumping media (disk, tape, etc)...
- [ ] I was retrieving media (disk, tape, etc) information...
- [ ] I was scanning media (disk, tape, etc)...
- [ ] I was retrieving device information...

### Description

When dumping this disc with a Plextor PX-760A, aaru crashes while inspecting the disc's geometry.  Notably, the message `Disc contains a hidden track...` appears in stdout immediately before the crash.  Transferring the disc into a Plextor PX-716A, aaru does not print that message, instead it prints `Checking mode for track 7...`.  The disc is multisession, so my guess is that there is some conflicting details in how the drive is reporting the multisession behavior back to aaru.

I re-dumped the disc with aaru v5.2, which succeeded in both the PX-716A and PX-760A drives and produced identical images; `aaru image compare` of the successful v5.2 (image 1) and v5.3 (image 2) disc images reports `Sector 135442 has different sizes (2324 bytes in image 1, 2352 in image 2) but are otherwise identical` for sectors 135442 through 135586.

I apologize for lacking some detail, but I thought it was important to log the bug even if I lacked the debug output, especially as I understand you may have a disc en route to you now.

### Exact command line used

sudo aaru media dump /dev/sr0 1998.11.01-Björk-All.is.Full.of.Love-US-63723.2-075596372329.aaru

### Expected behavior

Log produced by aaru v5.3 with Plextor PX-716A: [1998.11.01-Björk-All.is.Full.of.Love-US-63723.2-075596372329.log](https://github.com/aaru-dps/Aaru/files/7393631/1998.11.01-Bjork-All.is.Full.of.Love-US-63723.2-075596372329.log)

### Actual behavior

```
aaru 5.3.0+00000000 built by arkiva in Release
Copyright © 2011-2021 Natalia Portillo

Output image format: Aaru Format.
Device in database since 5/11/2021 11:48:31 PM.

Reading full TOC
Building track map...
Checking if drive supports PQ subchannel reading...
Checking if drive supports full raw subchannel reading...
Full raw subchannel reading supported...
Drive returns subchannel in BCD...
Calculating pregaps, can take some time...
Reading ATIP
Reading Disc Information
Reading PMA
Reading Session Information
Reading CD-Text from Lead-In
Solving lead-outs...
Detecting disc type...
Disc contains a hidden track...
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Aaru.Core.Devices.Dumping.Dump.CompactDisc()
   at Aaru.Core.Devices.Dumping.Dump.Mmc()
   at Aaru.Core.Devices.Dumping.Dump.Scsi()
   at Aaru.Core.Devices.Dumping.Dump.Start()
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Output of command execution with debug output enabled

```shell
I wasn't able to capture this output.  I was required to deliver the CD to the postal service just as I was investigating.
```

### Media details

https://www.discogs.com/release/13899-Bj%C3%B6rk-All-Is-Full-Of-Love

```
    Barcode (Text): 0 7559-63723-2 9
    Barcode (Scanned): 075596372329
    Barcode (Matrix area, Code 39): 044405
    Matrix / Runout (on 2 lines in matrix area): wea mfg. OLYPHANT
    Matrix / Runout: X9675 2 63723 RE-1 ECD01
    Matrix / Runout (Mother/Stamper Code): M1S1
    Mastering SID Code: ifpi L902
    Mould SID Code: IFPI 2V2X
    Other (on clear hub; "fg/" is reversed): WEAmfg/CA
```

**Comment by TheRogueArchivist** [comment]
According to someone who is able to reproduce this bug, this bug occurs with an iHAS624B drive as well. Two affected discs are http://redump.org/disc/86740/, http://redump.org/disc/76628/, and http://redump.org/disc/77030/.

**Comment by claunia** [comment]
As this bug is a crash and not a silent corruption of data, moved to 6.0 milestone.
