### ISSUE TITLE
"Object reference not set to an instance of an object." in DI.cs when running media info on BD-R/RE

### ISSUE THREAD

**Issue by TheRogueArchivist** [claunia/DiscImageChef#691]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Device manufacturer

Hitachi-LG Data Storage, Inc.

### Device model

BD-RE  BH08LS20 (FW 1.00)

### Bus the device uses to attach to the computer

- [ ] Parallel ATA
- [X] Serial ATA
- [ ] SCSI (any)
- [ ] ATAPI (mark above if parallel or serial)
- [ ] USB
- [ ] FireWire
- [ ] PCMCIA
- [ ] SecureDigital
- [ ] MultiMediaCard

### What were you doing when it failed?

- [ ] I was dumping media (disk, tape, etc)...
- [X] I was retrieving media (disk, tape, etc) information...
- [ ] I was scanning media (disk, tape, etc)...
- [ ] I was retrieving device information...

### Description

When running media info on this specific drive with BD-R/RE media, media info crashes. Two separate BD-R discs tried and one BD-RE.

### Exact command line used

aaru m info D:

### Expected behavior

Media info for the disc to be reported

### Actual behavior

Crash

### Output of command execution with debug output enabled

```shell
aaru 5.3.0+5c70b325 built by khepri in Debug, modified
Copyright c 2011-2021 Natalia Portillo

DEBUG (Media-Info command): --debug=True
DEBUG (Media-Info command): --device=D:
DEBUG (Media-Info command): --output-prefix=
DEBUG (Media-Info command): --verbose=False
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 6.0595 ms.
DEBUG (SCSI Device): INQUIRY took 1.7111 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 2.6542 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: False, Last Error: 0) took 1.706 ms.
DEBUG (SCSI Device): TEST UNIT READY took 1.6341 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 2.6334 ms.
DEBUG (SCSI Device): INQUIRY took 1.6995 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 4.1986 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: All, Sense: False, Last Error: 0) took 5.6197 ms.
DEBUG (SCSI Device): REPORT ASF (AGID: 0, Sense: False, Last Error: 0) took 1.3114 ms.
DEBUG (SCSI Device): READ CAPACITY took 1.6118 ms.
DEBUG (SCSI Device): READ CAPACITY(16) took 2.0247 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 2.9069 ms.
DEBUG (Media-Info command): GET CONFIGURATION current profile is 0041h
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: RecognizedFormatLayers, AGID: 0, Sense: False, Last Error: 0) took 3.0862 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Dvd, Address: 0, Layer Number: 0, Format: WriteProtectionStatus, AGID: 0, Sense: False, Last Error: 0) took 2.8524 ms.
DEBUG (SCSI Device): INVALIDATE AGID (AGID: 0, Sense: False, Last Error: 0) took 0.6151 ms.
DEBUG (SCSI Device): REPORT AGID CSS/CPPM (AGID: 0, Sense: False, Last Error: 0) took 1.3487 ms.
DEBUG (SCSI Device): SEND CHALLENGE (AGID: 0, Challenge System.Byte[], Sense: False, Last Error: 0) took 9.7207 ms.
DEBUG (SCSI Device): REPORT KEY1 (AGID: 0, Sense: True, Last Error: 0) took 2.3506 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Bd, Address: 0, Layer Number: 0, Format: DiscInformation, AGID: 0, Sense: False, Last Error: 0) took 3.0419 ms.
DEBUG (Media-Info command): READ DISC STRUCTURE: PAC
SCSI SENSE: ILLEGAL REQUEST
ILLEGAL FIELD IN CDB

DEBUG (Media-Info command): READ DISC STRUCTURE: DDS
SCSI SENSE: ILLEGAL REQUEST
ILLEGAL FIELD IN CDB

DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Bd, Address: 0, Layer Number: 0, Format: CartridgeStatus, AGID: 0, Sense: False, Last Error: 0) took 2.8611 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Bd, Address: 0, Layer Number: 0, Format: BdSpareAreaInformation, AGID: 0, Sense: False, Last Error: 0) took 3.1352 ms.
DEBUG (SCSI Device): READ DISC STRUCTURE (Media Type: Bd, Address: 0, Layer Number: 0, Format: RawDfl, AGID: 0, Sense: False, Last Error: 0) took 3.1008 ms.
DEBUG (SCSI Device): READ DISC INFORMATION (Data Type: TrackResources, Sense: False, Last Error: 0) took 1.3362 ms.
DEBUG (SCSI Device): READ DISC INFORMATION (Data Type: PowResources, Sense: True, Last Error: 0) took 2.104 ms.
DEBUG (Media-Info command): READ DISC INFORMATION 010b
SCSI SENSE: ILLEGAL REQUEST
ILLEGAL FIELD IN CDB

DEBUG (Media-Info command): READ MEDIA SERIAL NUMBER
SCSI SENSE: ILLEGAL REQUEST
INVALID COMMAND OPERATION CODE

DEBUG (SCSI Device): READ DISC INFORMATION (Data Type: DiscInformation, Sense: False, Last Error: 0) took 1.8959 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 3.6542 ms.
DEBUG (Media-Info command): GET CONFIGURATION current profile is 0041h
DEBUG (SCSI Device): READ CD (LBA: 0, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0.5554 ms.
DEBUG (SCSI Device): READ CD (LBA: 1, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0.5298 ms.
DEBUG (SCSI Device): READ CD (LBA: 2, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0.5891 ms.
DEBUG (SCSI Device): READ CD (LBA: 3, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0.6417 ms.
DEBUG (SCSI Device): READ CD (LBA: 4, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0.5713 ms.
DEBUG (SCSI Device): READ CD (LBA: 5, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 1.4876 ms.
DEBUG (SCSI Device): READ CD (LBA: 6, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0.5555 ms.
DEBUG (SCSI Device): READ CD (LBA: 7, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0.5859 ms.
DEBUG (SCSI Device): READ CD (LBA: 8, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0.6179 ms.
Media has 2992384 blocks of 2048 bytes/each. (for a total of 5.708 GiB)
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Aaru.Decoders.Bluray.DI.Prettify(Nullable`1 DIResponse) in /home/claunia/Development/Aaru/Aaru/Aaru.Decoders/Bluray/DI.cs:line 228
   at Aaru.Decoders.Bluray.DI.Prettify(Byte[] DIResponse) in /home/claunia/Development/Aaru/Aaru/Aaru.Decoders/Bluray/DI.cs:line 403
   at Aaru.Commands.Media.MediaInfoCommand.DoScsiMediaInfo(Boolean debug, String outputPrefix, Device dev) in /home/claunia/Development/Aaru/Aaru/Aaru/Commands/Media/Info.cs:line 411
   at Aaru.Commands.Media.MediaInfoCommand.Invoke(Boolean debug, Boolean verbose, String devicePath, String outputPrefix) in /home/claunia/Development/Aaru/Aaru/Aaru/Commands/Media/Info.cs:line 153
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Media details

Multiple BD-R/RE

**Comment by TheRogueArchivist** [comment]
Also present on "ATAPI   BD  O  DH4O3S" with firmware WH1E.
