### ISSUE TITLE
Errorneous "Disc contains a hidden track..." leads to crash reading multi-track CD-i disc Plextor PX-760SA

### ISSUE THREAD

**Issue by retrostuff** [claunia/DiscImageChef#703]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Device manufacturer

Plextor

### Device model

PX-760SA

### Bus the device uses to attach to the computer

- [ ] Parallel ATA
- [X] Serial ATA
- [ ] SCSI (any)
- [ ] ATAPI (mark above if parallel or serial)
- [ ] USB
- [ ] FireWire
- [ ] PCMCIA
- [ ] SecureDigital
- [ ] MultiMediaCard

### What were you doing when it failed?

- [X] I was dumping media (disk, tape, etc)...
- [ ] I was retrieving media (disk, tape, etc) information...
- [ ] I was scanning media (disk, tape, etc)...
- [ ] I was retrieving device information...

### Description

When dumping multi-track CD-i discs (not CD-i Ready), aaru crashes while inspecting the disc's geometry.

So far affected discs:
AntiStatic: http://redump.org/disc/77030/
Headcrash: http://redump.org/disc/86740/
Rosebud: http://redump.org/disc/76628/

### Exact command line used

aaru media dump -f -p 10 -v g: headcrash_test.aaruf

### Expected behavior

Dump the disc without error

### Actual behavior

Detecting disc type...
Disc contains a hidden track...
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no matching element

### Output of command execution with debug output enabled

```shell
DEBUG (Dump-Media command): --cicm-xml=
DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --device=g:
DEBUG (Dump-Media command): --encoding=
DEBUG (Dump-Media command): --first-pregap=False
DEBUG (Dump-Media command): --fix-offset=True
DEBUG (Dump-Media command): --force=True
DEBUG (Dump-Media command): --format=
DEBUG (Dump-Media command): --metadata=True
DEBUG (Dump-Media command): --options=
DEBUG (Dump-Media command): --output=headcrash_test.aaruf
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --retry-passes=10
DEBUG (Dump-Media command): --skip=512
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --trim=True
DEBUG (Dump-Media command): --verbose=True
DEBUG (Dump-Media command): --subchannel=any
DEBUG (Dump-Media command): --private=False
DEBUG (Dump-Media command): --fix-subchannel-position=True
DEBUG (Dump-Media command): --retry-subchannel=True
DEBUG (Dump-Media command): --fix-subchannel=False
DEBUG (Dump-Media command): --fix-subchannel-crc=False
DEBUG (Dump-Media command): --generate-subchannels=False
DEBUG (Dump-Media command): --skip-cdiready-hole=True
DEBUG (Dump-Media command): --eject=False
DEBUG (Dump-Media command): --max-blocks=64
DEBUG (Dump-Media command): --use-buffered-reads=True
DEBUG (Dump-Media command): --store-encrypted=True
DEBUG (Dump-Media command): --title-keys=True
DEBUG (Dump-Media command): Parsed options:
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 5,5357 ms.
DEBUG (SCSI Device): INQUIRY took 0,3768 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 1,4326 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: False, Last Error: 0) took 0,5735 ms.
Output image format: Aaru Format (49360069-1784-4a2f-b723-0c844d610b0a).
Device in database since 12.11.2021 19:41:05.
DEBUG (SCSI Device): TEST UNIT READY took 0,209 ms.

DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 2,7275 ms.
DEBUG (SCSI Device): MODE SENSE(10) took 0,9863 ms.
Reading full TOC
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 2, Track/Session Number: 0, Sense: False, LastError: 0) 1,0569 ms.
Building track map...
Checking if drive supports PQ subchannel reading...
DEBUG (SCSI Device): READ CD (LBA: 23550, Block Size: 2368, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Q16, Sense: False, Last Error: 0) took 1912,3324 ms.
Checking if drive supports full raw subchannel reading...
DEBUG (SCSI Device): READ CD (LBA: 23550, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 40,9765 ms.
Full raw subchannel reading supported...
DEBUG (SCSI Device): READ CD (LBA: 23660, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 48,1272 ms.
Drive returns subchannel in BCD...
Calculating pregaps, can take some time...
DEBUG (SCSI Device): READ CD (LBA: 11, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 104,9337 ms.
DEBUG (Pregap calculator): Subchannel is BCD
DEBUG (Pregap calculator): Skipping track 2
DEBUG (Pregap calculator): Skipping track 3
DEBUG (Pregap calculator): Skipping track 4
DEBUG (Pregap calculator): Skipping track 5
DEBUG (Pregap calculator): Skipping track 6
DEBUG (Pregap calculator): Skipping track 7
DEBUG (Pregap calculator): Skipping track 8
DEBUG (Pregap calculator): Skipping track 9
DEBUG (Pregap calculator): Skipping track 10
Reading ATIP
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 4, Track/Session Number: 0, Sense: False, LastError: 0) 0,5155 ms.
Reading Disc Information
DEBUG (SCSI Device): READ DISC INFORMATION (Data Type: DiscInformation, Sense: False, Last Error: 0) took 0,7271 ms.
Reading PMA
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 3, Track/Session Number: 0, Sense: False, LastError: 0) 0,4724 ms.
Reading Session Information
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 1, Track/Session Number: 0, Sense: False, LastError: 0) 0,4715 ms.
Reading CD-Text from Lead-In
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 5, Track/Session Number: 0, Sense: False, LastError: 0) 0,4381 ms.
Solving lead-outs...
Detecting disc type...
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 2,898 ms.
DEBUG (Media-Info command): GET CONFIGURATION current profile is 0008h
DEBUG (SCSI Device): READ TOC/PMA/ATIP took (MSF: True, Format: 4, Track/Session Number: 0, Sense: False, LastError: 0) 0,4242 ms.
DEBUG (Media detection): TOC says disc type is CD-i.
DEBUG (SCSI Device): READ CD (LBA: 0, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 23,5183 ms.
DEBUG (SCSI Device): READ CD (LBA: 1, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0,6668 ms.
DEBUG (SCSI Device): READ CD (LBA: 2, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0,9357 ms.
DEBUG (SCSI Device): READ CD (LBA: 3, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 1,0472 ms.
DEBUG (SCSI Device): READ CD (LBA: 4, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0,6334 ms.
DEBUG (SCSI Device): READ CD (LBA: 5, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 1,2132 ms.
DEBUG (SCSI Device): READ CD (LBA: 6, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 1,2442 ms.
DEBUG (SCSI Device): READ CD (LBA: 7, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 0,9819 ms.
DEBUG (SCSI Device): READ CD (LBA: 8, Block Size: 2352, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: None, Sense: False, Last Error: 0) took 1,2063 ms.
Disc contains a hidden track...
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Aaru.Core.Devices.Dumping.Dump.CompactDisc() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/CompactDisc/Dump.cs:line 568
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/MMC.cs:line 274
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/SCSI.cs:line 238
   at Aaru.Core.Devices.Dumping.Dump.Start() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 248
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by retrostuff** [comment]
[aaruminfo-w.zip](https://github.com/aaru-dps/Aaru/files/7560841/aaruminfo-w.zip)
