### ISSUE TITLE
Aaru crashes dumping Quake 2 with ASUS BW-16D1HT right before track 2

### ISSUE THREAD

**Issue by JTM-rootstorm** [claunia/DiscImageChef#711]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Device manufacturer

ASUS

### Device model

BW-16D1HT

### Bus the device uses to attach to the computer

- [ ] Parallel ATA
- [X] Serial ATA
- [ ] SCSI (any)
- [ ] ATAPI (mark above if parallel or serial)
- [X] USB
- [ ] FireWire
- [ ] PCMCIA
- [ ] SecureDigital
- [ ] MultiMediaCard

### USB cable or card reader manufacturer

OWC

### USB cable or card reader model

Mercury Pro

### What were you doing when it failed?

- [X] I was dumping media (disk, tape, etc)...
- [ ] I was retrieving media (disk, tape, etc) information...
- [ ] I was scanning media (disk, tape, etc)...
- [ ] I was retrieving device information...

### Description

Aaru crashes dumping Quake 2 with ASUS BW-16D1HT right before track 2. Have made successful dump on different drive

### Exact command line used

aaru media dump --force True --private True --speed 8 --retry-passes 8 "G:" ".\Quake2.aaruf"

### Expected behavior

Dump to finish fine

### Actual behavior

It crashes after trying to finish Track 1

### Output of command execution with debug output enabled

```shell
Reading sector 190208 of 311913 (1.463 MiB/sec.)DEBUG (SCSI Device): READ CD (LBA: 190208, Block Size: 2448, Transfer Length: 16, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: True, Last Error: 0) took 3.3618 ms.
DEBUG (SCSI Device): READ CD (LBA: 190208, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 0.503 ms.
DEBUG (SCSI Device): READ CD (LBA: 190209, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.43 ms.
DEBUG (SCSI Device): READ CD (LBA: 190210, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 0.3181 ms.
DEBUG (SCSI Device): READ CD (LBA: 190211, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 0.2763 ms.
DEBUG (SCSI Device): READ CD (LBA: 190212, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 0.2658 ms.
DEBUG (SCSI Device): READ CD (LBA: 190213, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 0.2418 ms.
DEBUG (SCSI Device): READ CD (LBA: 190214, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 0.2564 ms.
DEBUG (SCSI Device): READ CD (LBA: 190215, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 0.4017 ms.
DEBUG (SCSI Device): READ CD (LBA: 190216, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.5317 ms.
DEBUG (SCSI Device): READ CD (LBA: 190217, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.5441 ms.
DEBUG (SCSI Device): READ CD (LBA: 190218, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.5719 ms.
DEBUG (SCSI Device): READ CD (LBA: 190219, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.5797 ms.
DEBUG (SCSI Device): READ CD (LBA: 190220, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.5585 ms.
DEBUG (SCSI Device): READ CD (LBA: 190221, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.5596 ms.
DEBUG (SCSI Device): READ CD (LBA: 190222, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.614 ms.
DEBUG (SCSI Device): READ CD (LBA: 190223, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 1.5254 ms.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   at Aaru.Core.Devices.Dumping.Dump.ReadCdData(ExtentsULong audioExtents, UInt64 blocks, UInt32 blockSize, Double& currentSpeed, DumpHardwareType currentTry, ExtentsULong extents, IbgLog ibgLog, Double& imageWriteDuration, Int64 lastSector, ExtentsULong leadOutExtents, Double& maxSpeed, MhddLog mhddLog, Double& minSpeed, Boolean& newTrim, Boolean nextData, Int32 offsetBytes, Boolean read6, Boolean read10, Boolean read12, Boolean read16, Boolean readcd, Int32 sectorsForOffset, UInt32 subSize, MmcSubchannel supportedSubchannel, Boolean supportsLongSectors, Double& totalDuration, Track[] tracks, SubchannelLog subLog, MmcSubchannel desiredSubchannel, Dictionary`2 isrcs, String& mcn, HashSet`1 subchannelExtents, Dictionary`2 smallestPregapLbaPerTrack) in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/CompactDisc/Data.cs:line 629
   at Aaru.Core.Devices.Dumping.Dump.CompactDisc() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/CompactDisc/Dump.cs:line 1259
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/MMC.cs:line 274
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/SCSI.cs:line 238
   at Aaru.Core.Devices.Dumping.Dump.Start() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 248
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys) in /home/claunia/Development/Aaru/Aaru/Aaru/Commands/Media/Dump.cs:line 679
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()

any more and github is going to nuke everything and make me input it again
```

### Media details

0 47875 10195 1

https://www.ebay.com/itm/224743667664
https://www.ebay.com/itm/154677421506
https://www.ebay.com/itm/255328373075

**Comment by JTM-rootstorm** [comment]
Here's as much as my powershell instance will spit out before it decides I'm not allowed to scroll any more: https://nextcloud.wirelessram.com/s/Mn5EpTs8Zp9NQ7w

and the results of media info -w
https://nextcloud.wirelessram.com/s/eSoHySBNrKTBQTK

**Comment by TheRogueArchivist** [comment]
I am able to reproduce the bug on my end as well with my BW-16D1HT. Disc matches http://redump.org/disc/2569/ when dumped with DIC.

**Comment by claunia** [comment]
Cannot reproduce with the european version.

However because it is not a silent corruption, but an outright crash, it belongs in 6.0, moving the issue.

**Comment by claunia** [comment]
Confirmed reproduced with HL-DT-ST WH14NS40 fw 1.05
