### ISSUE TITLE
[ISO9660] "Error reading file: Sector address not found" while extracting heavily padded PS2 ISO9660 partition 

### ISSUE THREAD

**Issue by TheRogueArchivist** [claunia/DiscImageChef#721]
### Version

5.3.1

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Image format

ISO

### Application that created the image

DiscImageCreator

### What were you doing when it failed?

- [ ] I was converting the image to another format...
- [ ] I was retrieving image information...
- [ ] I was retrieving filesystem information...
- [ ] I was listing the filesystem contents...
- [X] I was extracting the filesystem contents...
- [ ] I was creating a metadata sidecar...
- [ ] I was checksumming the image...
- [ ] I was verifying the image...
- [ ] I was calculating the image entropy...

### Filesystem

ISO9660

### Description

When attempting to extract the ISO9660 filesystem from a PS2 disc image that is heavily padded (the file itself over 1 GB large, but compresses easily to around 40 MB), Aaru fails with the error "Error reading file: Sector address not found (Parameter 'sectorAddress')". 

### Exact command line used

Aaru fs extract '.\Jumanji (Australia).iso' ./test

### Expected behavior

Aaru to successfully extract the contents of the filesystem.

### Actual behavior

Aaru crashes.

### Output of command execution with debug output enabled

```shell
...
DEBUG (ISO9660 Plugin): Sector 1019, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 1020, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 1021, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 1022, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 1023, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 1024, Cooked, Mode 0/1 / Mode 2 Form 1
DEBUG (ISO9660 Plugin): Sector 1025, Cooked, Mode 0/1 / Mode 2 Form 1
Written 1525448 bytes of file SLES_544.36 to ./test\ISO9660\NO NAME\SLES_544.36
DEBUG (ISO9660 Plugin): Sector 280, Cooked, Mode 0/1 / Mode 2 Form 1
Written 56 bytes of file SYSTEM.CNF to ./test\ISO9660\NO NAME\SYSTEM.CNF
Error reading file: Sector address not found (Parameter 'sectorAddress')
DEBUG (Extract-Files command):    at Aaru.DiscImages.ZZZRawImage.ReadSectors(UInt64 sectorAddress, UInt32 length) in /home/claunia/Development/Aaru/Aaru/Aaru.Images/ZZZRawImage/Read.cs:line 1234
   at Aaru.DiscImages.ZZZRawImage.ReadSector(UInt64 sectorAddress) in /home/claunia/Development/Aaru/Aaru/Aaru.Images/ZZZRawImage/Read.cs:line 1223
   at Aaru.Filesystems.ISO9660.ReadSector(UInt64 sector, Boolean interleaved, Byte fileNumber) in /home/claunia/Development/Aaru/Aaru/Aaru.Filesystems/ISO9660/Mode2.cs:line 68
   at Aaru.Filesystems.ISO9660.ReadWithExtents(Int64 offset, Int64 size, List`1 extents, Boolean interleaved, Byte fileNumber) in /home/claunia/Development/Aaru/Aaru/Aaru.Filesystems/ISO9660/File.cs:line 528
   at Aaru.Filesystems.ISO9660.Read(String path, Int64 offset, Int64 size, Byte[]& buf) in /home/claunia/Development/Aaru/Aaru/Aaru.Filesystems/ISO9660/File.cs:line 159
   at Aaru.Commands.Filesystem.ExtractFilesCommand.ExtractFilesInDir(String path, IReadOnlyFilesystem fs, String volumeName, String outputDir, Boolean doXattrs) in /home/claunia/Development/Aaru/Aaru/Aaru/Commands/Filesystem/ExtractFiles.cs:line 489
   at Aaru.Commands.Filesystem.ExtractFilesCommand.Invoke(Boolean debug, Boolean verbose, String encoding, Boolean xattrs, String imagePath, String namespace, String outputDir, String options) in /home/claunia/Development/Aaru/Aaru/Aaru/Commands/Filesystem/ExtractFiles.cs:line 289
```

### Affected image

http://redump.org/disc/52293/

**Comment by claunia** [comment]
Test it with `devel`

**Comment by TheRogueArchivist** [comment]
No crash on b05dc45d, but seems to hang on "Reading file PAD.TXT... ----------------------------------------   0%".
