### ISSUE TITLE
Dumping large hard disks to Aaru format fails assertion when hashing sectors

### ISSUE THREAD

**Issue by kkaisershot** [claunia/DiscImageChef#722]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Device manufacturer

Maxtor

### Device model

6B160M0

### Bus the device uses to attach to the computer

- [ ] Parallel ATA
- [X] Serial ATA
- [ ] SCSI (any)
- [ ] ATAPI (mark above if parallel or serial)
- [ ] USB
- [ ] FireWire
- [ ] PCMCIA
- [ ] SecureDigital
- [ ] MultiMediaCard

### What were you doing when it failed?

- [X] I was dumping media (disk, tape, etc)...
- [ ] I was retrieving media (disk, tape, etc) information...
- [ ] I was scanning media (disk, tape, etc)...
- [ ] I was retrieving device information...

### Description

Dumping large (over 100GB) hard disks to Aaru format results in a "System.Exception: Assertion failed" at SpamSumContext.cs:119 upon nearly completing hashing sectors. I encountered this with a 160GB drive.

Note that the dropdown in the bug report form only lets me select 5.3.0, however I was also able to reproduce this in 5.3.1, both release and debug builds.

### Exact command line used

./aaru media dump -O compress=False,deduplicate=False -v -d /dev/sdb /mnt/B42HDP2H.aaruf 2>&1 | tee output.txt

### Expected behavior

Hashing sectors should complete without error, proceeding to close the image.

### Actual behavior

<pre>Hashing sector 320172992 of 320173056Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---&gt; System.Exception: Assertion failed
   at Aaru.Checksums.SpamSumContext.End() in /home/claunia/Development/Aaru/Aaru/Aaru.Checksums/SpamSumContext.cs:line 119
   at Aaru.Core.Checksum.End() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Checksum.cs:line 491
   at Aaru.Core.Sidecar.BlockMedia(IMediaImage image, Guid filterId, String imagePath, FileInfo fi, PluginBase plugins, List`1 imgChecksums, CICMMetadataType& sidecar, Encoding encoding) in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Sidecar/BlockMedia.cs:line 365
   at Aaru.Core.Sidecar.Create() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Sidecar/Sidecar.cs:line 155
   at Aaru.Core.Devices.Dumping.Dump.Sbc(Dictionary`2 mediaTags, MediaType dskType, Boolean opticalDisc, Dump dvdDecrypt) in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/Sbc/Dump.cs:line 1006
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/SCSI.cs:line 251
   at Aaru.Core.Devices.Dumping.Dump.Start() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 248
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys) in /home/claunia/Development/Aaru/Aaru/Aaru/Commands/Media/Dump.cs:line 679
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.&lt;&gt;c__DisplayClass4_0.&lt;&lt;BuildInvocationChain&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c.&lt;&lt;UseParseErrorReporting&gt;b__19_0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c__DisplayClass14_0.&lt;&lt;UseHelp&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c__DisplayClass22_0.&lt;&lt;UseVersionOption&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c__DisplayClass21_0.&lt;&lt;UseTypoCorrections&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c.&lt;&lt;UseSuggestDirective&gt;b__20_0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c.&lt;&lt;UseParseDirective&gt;b__18_0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c.&lt;&lt;UseDebugDirective&gt;b__10_0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c.&lt;&lt;RegisterWithDotnetSuggest&gt;b__9_0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.&lt;&gt;c__DisplayClass12_0.&lt;&lt;UseExceptionHandler&gt;b__0&gt;d.MoveNext()
Uploading statistics
</pre>

### Output of command execution with debug output enabled

```shell
Using the command line provided, I generated a full log from a debug build, however owing to its size, I bzip2 compressed it and am hosting it on Dropbox for the time being:

https://www.dropbox.com/s/wr5uwqowdbhkq03/output.txt.bz2?dl=0
```

### Media details

Maxtor DiamondMax 10
Model:6B160M0
160GB SATA150 HDD
LBA: 320173056

**Comment by TheRogueArchivist** [comment]
May be a bug in calculating the SpamSum checksum, which will no longer be performed by default in 6.0. As a workaround for the time being, you can run the media dump command with “—metadata False” to bypass the checksumming. To retrieve the checksums after the initial dump, you can use the image checksum command, and use “—spamsum False” to hopefully skip the checksum that appears to be crashing.

**Comment by claunia** [comment]
It's already fixed, hashing disks of 250Gb works.
