### ISSUE TITLE
DiscImageChef not working in Windows 

### ISSUE THREAD

**Issue by JoeLin17** [claunia/DiscImageChef#73]
Download the latest code and commented out the following code and rebuild:

```
     if(!System.IO.File.Exists(options.DevicePath))
            {
                DicConsole.ErrorWriteLine("Specified device does not exist.");
                return;
            }
```
Running DiscImageChef in Windows 7 with the following command raised the following exception:

`DiscImageChef media-scan -i e:`

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'ioctl' in DLL 'Kernel32.dll'.
   at DiscImageChef.Devices.Windows.Extern.DeviceIoControlScsi(SafeFileHandle hDevice, WindowsIoctl IoControlCode, ScsiPassThroughDirectAndSenseBuffer& InBuffer, UInt32 nInBufferSize, ScsiPassThroughDirectAndSenseBuffer& OutBuffer, UInt32 n
OutBufferSize, UInt32& pBytesReturned, IntPtr Overlapped)   at DiscImageChef.Devices.Windows.Command.SendScsiCommand(SafeFileHandle fd, B
yte[] cdb, Byte[]& buffer, Byte[]& senseBuffer, UInt32 timeout, ScsiIoctlDirection direction, Double& duration, Boolean& sense) in ..\Documents\DiscImageChef\DiscImageChef.Devices\Windows\Command.cs:line 81   at DiscImageChef.Devices.Command.SendScsiCommand(PlatformID ptID, Object fd,
Byte[] cdb, Byte[]& buffer, Byte[]& senseBuffer, UInt32 timeout, ScsiDirection direction, Double& duration, Boolean& sense) in ..\Documents\DiscImageChef\DiscImageChef.Devices\Command.cs:line 95   at DiscImageChef.Devices.Device.SendScsiCommand(Byte[] cdb, Byte[]& buffer, Byte[]& senseBuffer, UInt32 timeout, ScsiDirection direction, Double& duration, Boolean& sense) in ..\Documents\DiscImageChef\DiscImageChef.Devices\Device\Commands.cs:line 52
   at DiscImageChef.Devices.Device.ScsiInquiry(Byte[]& buffer, Byte[]& senseBuffer, UInt32 timeout, Double& duration) in ..\Documents\DiscImageChef\DiscImageChef.Devices\Device\ScsiCommands\SPC.cs:line 91
   at DiscImageChef.Devices.Device.ScsiInquiry(Byte[]& buffer, Byte[]& senseBuffer, UInt32 timeout) in ..\Documents\DiscImageChef\DiscImageChef.Devices\Device\ScsiCommands\SPC.cs:line 73
   at DiscImageChef.Devices.Device.ScsiInquiry(Byte[]& buffer, Byte[]& senseBuffer) in ..\Documents\DiscImageChef\DiscImageChef.Devices\Device\ScsiCommands\SPC.cs:line 48
   at DiscImageChef.Devices.Device..ctor(String devicePath) in ..\Documents\DiscImageChef\DiscImageChef.Devices\Device\Constructor.cs:line 99

   at DiscImageChef.Commands.MediaScan.doMediaScan(MediaScanOptions options) in
..\Documents\DiscImageChef\DiscImageChef\Commands\MediaScan.c
s:line 69
   at DiscImageChef.MainClass.<>c.<Main>b__0_9(MediaScanOptions opts) in ..\Documents\DiscImageChef\DiscImageChef\Main.cs:line 153
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action) in ..\Documents\DiscImageChef\commandline\src\CommandLine\ParserResultExtensions.cs:line 45
   at DiscImageChef.MainClass.Main(String[] args) in ..\Documents\DiscImageChef\DiscImageChef\Main.cs:line 51

Is the command `DiscImageChef media-scan -i e:` correct in Windows?

**Comment by claunia** [comment]
Please edit the comment and paste the extension in a comment block for readability, thanks.

**Comment by claunia** [comment]
Refer to #74 for details and progress.

**Comment by JoeLin17** [comment]
What you mean by "paste the extension"? I am not familiar with that,

**Comment by claunia** [comment]
@JoeLin17 sorry that was autocorrection kicking in, correct term "exception". Doesn't matter already saw where's the problem, check #74.
