### ISSUE TITLE
Every command causes a crash

### ISSUE THREAD

**Issue by daviunic** [claunia/DiscImageChef#78]
Running any command with various image types (Apridisk, raw) results in a crash:

```
Unhandled Exception: System.ArgumentException: Object type cannot be converted to target type.
   at System.RuntimeFieldHandle.SetValueDirect(RtFieldInfo field, RuntimeType fieldType, Void* pTypedRef, Object value, RuntimeType contextType)
   at System.Reflection.RtFieldInfo.SetValueDirect(TypedReference obj, Object value)
   at DiscImageChef.BigEndianMarshal.SwapStructureMembersEndian[T](T str)
   at DiscImageChef.BigEndianMarshal.ByteArrayToStructureBigEndian[T](Byte[] bytes)
   at DiscImageChef.Filters.AppleSingle.Identify(String path)
   at DiscImageChef.Filters.FiltersList.GetFilter(String path)
   at DiscImageChef.Commands.ExtractFiles.doExtractFiles(ExtractFilesOptions options)
   at DiscImageChef.MainClass.<>c.<Main>b__0_16(ExtractFilesOptions opts)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DiscImageChef.MainClass.Main(String[] args)
```

Version 3.5.99.0.

**Comment by claunia** [comment]
Solved in c7f4d72cc65c54c02af90248798814f5deac40d8.
