### ISSUE TITLE
[UnitTest] [RayDIM] Hashes are not as expected

### ISSUE THREAD

**Issue by claunia** [claunia/DiscImageChef#785]
### Version

Development commit

### Commit hash

HEAD

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [ ] An Intel or AMD
- [X] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Description

Hashes returned from RayDIM images are not as expected.

### Exact command line used

Unit test

### Expected behavior

Unknown, needs more investigation.

### Actual behavior

Hashes are not as expected.

### Output of command execution with debug output enabled

```shell
Multiple failures or warnings in test:
  1)   Hash: 5f1dd8.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "c109e802e65365245dedd1737ec65c92"
  But was:  "aeef05636add7b371b5128073b36f945"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  2)   Hash: 5f1dd8_pass.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "d6eb723ac53eb469f64d8df69efef3dd"
  But was:  "59e3fecd9501694f897dbce45aa41946"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  3)   Hash: 5f1dd.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "a327c34060570e1a917eb1d88716a11a"
  But was:  "c064dc6c091ebfd811223e0f25ba76c9"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  4)   Hash: 5f1dd_pass.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "b9807f1c25bf472633e7e80fa947a4d1"
  But was:  "d37559bca656484e2c91cee941f9d22b"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  5)   Hash: 5f2dd8.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "8b9e6662ef25a08d167f7ec4436efac8"
  But was:  "b9d1e5d5dd5bb7d1d865ed138d87ec00"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  6)   Hash: 5f2dd8_pass.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "532694cde41f1553587b65c528bc185b"
  But was:  "d865778a7b9294045d3341be57fa9278"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  7)   Hash: 5f2dd.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "a0b2aa16acaab9f521dff74ba93485ae"
  But was:  "f63b977a86a9f8ef46151a1ace30b755"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  8)   Hash: 5f2dd_pass.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "934e3a0f07410d0f4750f2beb3ce48f1"
  But was:  "efe65433ade25ce4d03d0f6a0c199b85"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  9)   Hash: 5f2hd.dim.lz
  String lengths are both 32. Strings differ at index 1.
  Expected: "78819708381987b3120fc777a5f08f2d"
  But was:  "76d507db9dde141d79296c93d009bcc3"
  ------------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  10)   Hash: 5f2hd_pass.dim.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "37dbeabaf72384870284ccd102b85eb7"
  But was:  "84b0b7b0b13f10b719ad3ff3ddf1b8ac"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  11)   Hash: DSKA0058.DIM.lz
  String lengths are both 32. Strings differ at index 1.
  Expected: "a7688d6be942272ce866736e6007bc46"
  But was:  "a9bacb3d24afd8894b4857d4ca15f1a2"
  ------------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  12)   Hash: DSKA0060.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "ef0c3da4749da2f79d7d623d9b6f3d4d"
  But was:  "df4f196d4133f29e2735c05bb15ff6bf"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  13)   Hash: DSKA0061.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "5231d2e8a99ba5f8dfd16ca1a05f40cd"
  But was:  "630f017f692e853278ab108474fc1fa5"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  14)   Hash: DSKA0083.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "952f33314fb930c2d02ef4604585c0e6"
  But was:  "0373d3d489e98cc1160da9b0412f6df0"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  15)   Hash: DSKA0085.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "53dfcaceed8203ee629fc7fe520e1217"
  But was:  "2e9910e2d637eb88d58056b61a25401c"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  16)   Hash: DSKA0157.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "3a7f25fa38019109e89051993076063a"
  But was:  "b4955c463dcbe0744c4ac0bee23d62fe"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  17)   Hash: DSKA0170.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "0c043ceba489ef80c1b7f58534af12f5"
  But was:  "60fef9861bd893150aafd7751f886155"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  18)   Hash: DSKA0176.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "ca53f9cc4dcd04d06f5c4c3df09195ab"
  But was:  "a4337668ae19b79276fba4f7499ea936"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  19)   Hash: DSKA0177.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "fde94075cb3fd1c52af32062b0251af0"
  But was:  "b592e975a673226ba0880aece6ebc9e2"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  20)   Hash: DSKA0181.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "4375fe3d7e50a5044b4850d8542363fb"
  But was:  "63b68958663987b2281b2105e704d3ce"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  21)   Hash: DSKA0232.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "53a50481d90228f527b72f058de257da"
  But was:  "ed03778299e16ace99383487bff2228a"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  22)   Hash: DSKA0265.DIM.lz
  String lengths are both 32. Strings differ at index 0.
  Expected: "2b2c891ef5edee8518a1ae2ed3ab71a0"
  But was:  "83e62bbb301ed40d9744593b7dc05f9e"
  -----------^
   at Aaru.Tests.Images.BlockMediaImageTest.<>c__DisplayClass4_0.<Hashes>b__0() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 127
   at NUnit.Framework.Assert.Multiple(TestDelegate testDelegate)
   at Aaru.Tests.Images.BlockMediaImageTest.Hashes() in /Users/claunia/Development/Aaru/Aaru/Aaru.Tests/Images/BlockMediaImageTest.cs:line 77

  23)   Hash: DSKA0270.DIM.lz
```

**Comment by claunia** [comment]
After extensive checks we've seen that the original software has some problems reading and specially writing back some not-so-standard floppy formats, but Aaru definitively is extracting the data as it is in the image.
