### ISSUE TITLE
Unhandled exception when dumping Moto Racer 2 CD

### ISSUE THREAD

**Issue by Switch123456789** [claunia/DiscImageChef#803]
### Version

5.3.0

### Commit hash

5.3.2+a3f639a1

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Device manufacturer

Lenovo

### Device model

Slim_USB_Burner_8L32

### Bus the device uses to attach to the computer

- [ ] Parallel ATA
- [ ] Serial ATA
- [ ] SCSI (any)
- [ ] ATAPI (mark above if parallel or serial)
- [X] USB
- [ ] FireWire
- [ ] PCMCIA
- [ ] SecureDigital
- [ ] MultiMediaCard

### What were you doing when it failed?

- [X] I was dumping media (disk, tape, etc)...
- [ ] I was retrieving media (disk, tape, etc) information...
- [ ] I was scanning media (disk, tape, etc)...
- [ ] I was retrieving device information...

### Description

Dumpig Moto Racer 2 CD is causing a crash. Since the log is over 60.000 lines long and my terminal can't hold this much lines, I will trim it to only include the lines right before the error & add the log-file.

### Exact command line used

aaru media dump --debug --verbose --first-pregap true --persistent true --fix-subchannel-crc true --fix-offset true --generate-subchannels --eject true /dev/sr0 test/disc1/disc1.aaru

### Expected behavior

Aaru completing the dump.

### Actual behavior

Aaru keeps trowing error "Unhandlet exception" on the same place.

### Output of command execution with debug output enabled

```shell
> LOG-FILE
Start logging at 2/21/2023 4:22:34 PM
################# System information #################
Linux 6.1.11.1 (64-bit)
.NET Core 

################# Program information ################
Aaru 5.3.2+a3f639a1
Running in 64-bit
Running as superuser: No
Command line: /opt/Aaru/aaru.dll media dump --debug --verbose --first-pregap true --persistent true --fix-subchannel-crc true --fix-offset true --generate-subchannels --eject true /dev/sr0 test/disc1/disc1.aaru

################# Device information #################
Manufacturer: Lenovo
Model: Slim_USB_Burner
Firmware revision: 8L32
Serial number: 111080110515
Removable device: True
Device type: ATAPI
CompactFlash device: False
PCMCIA device: False
USB device: True
USB manufacturer: USB2.0 External
USB product: Mass Storage Device
USB serial: 111080110515
USB vendor ID: 17EFh
USB product ID: 7306h
FireWire device: False
######################################################

################ Dumping progress log ################
2023-02-21T16:22:34 Output image format: Aaru Format (49360069-1784-4a2f-b723-0c844d610b0a).
2023-02-21T16:22:34 Device not in database, please create a device report and attach it to a Github issue.
2023-02-21T16:22:34 Device reports current profile is 0x0008
2023-02-21T16:22:34 Reading full TOC
2023-02-21T16:22:35 Building track map...
2023-02-21T16:22:35 Checking if drive supports PQ subchannel reading...
2023-02-21T16:22:35 Checking if drive supports full raw subchannel reading...
2023-02-21T16:22:35 Full raw subchannel reading supported...
2023-02-21T16:22:35 Drive returns subchannel in BCD...
2023-02-21T16:22:35 Calculating pregaps, can take some time...
2023-02-21T16:24:44 Could not read subchannel for sector 326137
2023-02-21T16:26:53 Could not read subchannel for sector 326138
2023-02-21T16:29:01 Could not read subchannel for sector 326139
2023-02-21T16:31:10 Could not read subchannel for sector 326140
2023-02-21T16:33:19 Could not read subchannel for sector 326141
2023-02-21T16:33:19 WARNING: The drive has returned incorrect Q positioning when calculating pregaps. A best effort has been tried but they may be incorrect.
2023-02-21T16:33:19 Reading ATIP
2023-02-21T16:33:19 Reading Disc Information
2023-02-21T16:33:19 Reading PMA
2023-02-21T16:33:19 Reading Session Information
2023-02-21T16:33:19 Reading CD-Text from Lead-In
2023-02-21T16:33:20 Detecting disc type...
2023-02-21T16:33:21 Checking mode for track 1...
2023-02-21T16:33:21 Track 1 is MODE1
2023-02-21T16:33:21 Checking mode for track 17...
2023-02-21T16:33:21 Track 17 is MODE2 FORM 1
2023-02-21T16:33:22 Reading first track pregap
2023-02-21T16:33:37 Got 142 first track pregap sectors.
2023-02-21T16:33:37 Reading 32 sectors at a time.
2023-02-21T16:33:37 Device reports 335478 blocks (821250144 bytes).
2023-02-21T16:33:37 Device can read 32 blocks at a time.
2023-02-21T16:33:37 Device reports 2448 bytes per logical block.
2023-02-21T16:33:37 SCSI device type: MultiMediaDevice.
2023-02-21T16:33:37 Media identified as CDROMXA.
2023-02-21T16:33:37 Creating subchannel log in test/disc1/disc1.sub.log
2023-02-21T16:33:37 Setting flags for track 1...
2023-02-21T16:33:37 Setting flags for track 2...
2023-02-21T16:33:37 Setting flags for track 3...
2023-02-21T16:33:37 Setting flags for track 4...
2023-02-21T16:33:37 Setting flags for track 5...
2023-02-21T16:33:37 Setting flags for track 6...
2023-02-21T16:33:37 Setting flags for track 7...
2023-02-21T16:33:37 Setting flags for track 8...
2023-02-21T16:33:37 Setting flags for track 9...
2023-02-21T16:33:37 Setting flags for track 10...
2023-02-21T16:33:37 Setting flags for track 11...
2023-02-21T16:33:37 Setting flags for track 12...
2023-02-21T16:33:37 Setting flags for track 13...
2023-02-21T16:33:37 Setting flags for track 14...
2023-02-21T16:33:37 Setting flags for track 15...
2023-02-21T16:33:37 Setting flags for track 16...
2023-02-21T16:33:37 Setting flags for track 17...
2023-02-21T16:33:37 Drive reading offset is 24 bytes (6 samples).
2023-02-21T16:33:37 Disc write offset is unknown, dump may not be correct.
2023-02-21T16:33:37 Setting speed to MAX for data reading.
2023-02-21T16:33:38 Setting index 1 for track 1 to LBA 0.


> CONSOLE-OUTPUT
DEBUG (SCSI Device): READ CD (LBA: 160155, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 2 ms.
DEBUG (SCSI Device): READ CD (LBA: 160156, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 13 ms.
DEBUG (SCSI Device): READ CD (LBA: 160157, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 2 ms.
DEBUG (SCSI Device): READ CD (LBA: 160158, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 2 ms.
DEBUG (SCSI Device): READ CD (LBA: 160159, Block Size: 2448, Transfer Length: 1, Expected Sector Type: AllTypes, DAP: False, Relative Address: False, Sync: True, Headers: AllHeaders, User Data: True, ECC/EDC: True, C2: None, Subchannel: Raw, Sense: False, Last Error: 0) took 2 ms.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at Aaru.Core.Devices.Dumping.Dump.ReadCdData(ExtentsULong audioExtents, UInt64 blocks, UInt32 blockSize, Double& currentSpeed, DumpHardwareType currentTry, ExtentsULong extents, IbgLog ibgLog, Double& imageWriteDuration, Int64 lastSector, ExtentsULong leadOutExtents, Double& maxSpeed, MhddLog mhddLog, Double& minSpeed, Boolean& newTrim, Boolean nextData, Int32 offsetBytes, Boolean read6, Boolean read10, Boolean read12, Boolean read16, Boolean readcd, Int32 sectorsForOffset, UInt32 subSize, MmcSubchannel supportedSubchannel, Boolean supportsLongSectors, Double& totalDuration, Track[] tracks, SubchannelLog subLog, MmcSubchannel desiredSubchannel, Dictionary`2 isrcs, String& mcn, HashSet`1 subchannelExtents, Dictionary`2 smallestPregapLbaPerTrack)
   at Aaru.Core.Devices.Dumping.Dump.CompactDisc()
   at Aaru.Core.Devices.Dumping.Dump.Mmc()
   at Aaru.Core.Devices.Dumping.Dump.Scsi()
   at Aaru.Core.Devices.Dumping.Dump.Start()
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Media details
![image](https://user-images.githubusercontent.com/25269380/220390173-6261f025-93e1-4b6d-8ada-3851b38237eb.png)

![image](https://user-images.githubusercontent.com/25269380/220396050-b6ed4c09-7db2-407f-b757-ac373990ab76.png)

**Comment by Switch123456789** [comment]
Today I tried it again (same OS, same drive, same disk) and aaru succeeded this time.
Version: `6.0.0~alpha9+4825d414.4825d414604fe30e23ceabc169be94f1b0dcd781`

**Comment by claunia** [comment]
Can you confirm 5.3.2 is, indeed, still failing?

**Comment by Switch123456789** [comment]
> Can you confirm 5.3.2 is, indeed, still failing?

2 to 5 months ago (not sure exactly) I tried `5.3.?` and it still failed. I can test again with the latest v5 if necessary. Can I downgrade on arch without issues?

**Comment by claunia** [comment]
should have no issue to downgrade

**Comment by Switch123456789** [comment]
I gave v5 a shot, it still fails with the same error message.
